# Test with: bundle exec jekyll serve
title: mdbrown.dev
email: matt@mdbrown.dev
url: "https://mdbrown.dev"
github_username: m-d-brown
google_analytics_id: G-S5WY5QYVVJ

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - script/
  - vendor/
  - .bundle/
  - .ruby-lsp/
  - .jekyll-cache/
  - .sass-cache/
